# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-4X45TG13L1'

menu:

- {name: 'Learning Resources', url: 'resources'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://instagram.com/isaacbroyles.art'}
- {icon: 'tiktok', link:  'https://www.tiktok.com/@isaacbroyles.art'}
- {icon: 'youtube', link:  'https://www.youtube.com/channel/UCyfgmTybegqIIIdoJ_JzuKw'}
- {icon: 'pinterest', link:   'https://www.pinterest.com/isaacbroyles_art/'}
- {icon: 'facebook', link:   'https://www.facebook.com/isaacbroyles.art'}
- {icon: 'twitter', link:    'https://twitter.com/isaacbroyles'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
